# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95ebb725522f1b6d746d1f6c728a73b9"
name = "Tensor Search Extension"
handle = "tensor-search-extension"
application_url = "https://captured-analog-msgid-introducing.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://captured-analog-msgid-introducing.trycloudflare.com/auth/callback", "https://captured-analog-msgid-introducing.trycloudflare.com/auth/shopify/callback", "https://captured-analog-msgid-introducing.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
